# Generated by Django 3.0 on 2019-12-10 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timestramp',
            new_name='timestamp',
        ),
    ]
